/** Deterministic, original demonstration: an open architectural vessel with a bridge. */
export function createSampleGcode(): string {
  const lines = [
    '; Generated by XPYEngine web preview demo',
    '; filament_diameter = 1.75',
    'G21',
    'G90',
    'M83',
  ];
  const pushPath = (
    points: number[][],
    role: string,
    z: number,
    width = 0.46,
  ) => {
    lines.push(
      `; FEATURE: ${role}`,
      `; LINE_WIDTH: ${width}`,
      `G0 X${points[0][0].toFixed(3)} Y${points[0][1].toFixed(3)} Z${z.toFixed(3)}`,
    );
    for (let i = 1; i < points.length; i++) {
      const length = Math.hypot(
        points[i][0] - points[i - 1][0],
        points[i][1] - points[i - 1][1],
      );
      const extrusion = (length * width * 0.24) / ((Math.PI * 1.75 ** 2) / 4);
      lines.push(
        `G1 X${points[i][0].toFixed(3)} Y${points[i][1].toFixed(3)} E${extrusion.toFixed(5)} F2400`,
      );
    }
  };
  const ring = (radius: number, z: number) =>
    Array.from({ length: 121 }, (_, index) => {
      const angle = (index / 120) * Math.PI * 2;
      const r = radius + Math.cos(angle * 6 + z * 0.028) * 2.8;
      return [r * Math.cos(angle), r * Math.sin(angle)];
    });
  for (let layer = 0; layer < 144; layer++) {
    const z = (layer + 1) * 0.24;
    const radius = 24 + 6 * Math.sin((layer / 143) * Math.PI * 0.9);
    lines.push(
      '; CHANGE_LAYER',
      `; Z_HEIGHT: ${z.toFixed(3)}`,
      '; LAYER_HEIGHT: 0.24',
    );
    if (layer < 3) pushPath(ring(34 + layer * 0.5, z), 'Skirt', z);
    pushPath(ring(radius, z), layer === 143 ? 'Top surface' : 'Outer wall', z);
    pushPath(ring(radius - 0.48, z), 'Inner wall', z);
    pushPath(ring(radius - 0.96, z), 'Inner wall', z);
    if (layer < 5) {
      for (let y = -19; y <= 19; y += layer < 2 ? 0.8 : 3) {
        const x = Math.sqrt(20 ** 2 - y ** 2);
        pushPath(
          [
            [-x, y],
            [x, y],
          ],
          layer < 2 ? 'Bottom surface' : 'Sparse infill',
          z,
        );
      }
    }
    // A central bridge with sacrificial support, visible when outer walls are hidden.
    if (layer >= 5 && layer < 96) {
      for (let x = -16; x <= 16; x += 3)
        pushPath(
          [
            [x, -2.5],
            [x, 2.5],
          ],
          layer >= 92 ? 'Support interface' : 'Support',
          z,
          0.38,
        );
    }
    if (layer >= 96 && layer < 102) {
      for (let y = -3; y <= 3; y += 0.5)
        pushPath(
          [
            [-radius + 1, y],
            [radius - 1, y],
          ],
          layer === 96 ? 'Bridge' : 'Top surface',
          z,
        );
    }
  }
  return lines.join('\n');
}
